### ISSUE TITLE
Can't set systemVersion for output json

### ISSUE THREAD

**Issue by LeonidEfremov** [bronumski/HealthNet#4]
No ability to manage value of systemVersion parameter. Also, will be great to display this systemVersion on Dashboard.

**Comment by bronumski** [comment]
@LeonidEfremov - Again sorry I didn't get a notification of issues being created.

Could you give a bit more detail as to what your expectations are?

**Comment by bronumski** [comment]
Actually I think I know what you are after. By default the `systemVersion` is pulled from the assembly file version using the `VersionProvider` however if you want to do something else you can implement the `IVersionProvider` yourself and pull the version from elsewhere but in order to do this you need to create the `HealthCheckService` yourself. The WebApi/Nancy and Owin components don't allow you to do this. Maybe this is something I can improve on.

Let me know if this would address your issue?

**Comment by bronumski** [comment]
@LeonidEfremov - Did you ever get this working? With the new aspnet core package you asked for (#5) injecting in your own `VersionProvider` is easier.

I will update the docs later.

**Comment by bronumski** [comment]
Allowing the version provider to be injected to the various platforms has been addressed by doing #5. Docs have been updated too. In terms of the dashboard I wasn't expecting anyone to actually use it directly but just show it as a proof of concept. Maybe I will take a look at including the version number later but closing this for now.
